name: Kunstfotograf.no
favicon: null
layout_spectrum: 0.577366067096591
typography_spectrum: 0.29438034002669156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.23074351251125336
  lightness: 0.4563752051908523
  saturation: 0.4069425710476935
  rhythmicContrast: 0.08057256112806499
purpose: []
